development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:a092e99508ba1c3f1a8ccea022ac0022@pearlfish.redistogo.com:9807/
  channel_prefix: snack_production
